export const PortfolioList = [
    {
        id: '1',
        name: 'KATEKIMA',
        image: ["katekima", "katekima-2", "katekima-3", "katekima-4", "katekima-5", "katekima-6", "katekima-7", "katekima-8", "katekima-9", "katekima-10"],
        link: 'https://github.com/vincentalexx/KATEKIMA.git',
        deploy: '',
        langs: ['PHP', 'Laravel', 'MySQL'],
        description: 'Katekima is a photocopy company warehouse database management that allows admin to add a new product, add and remove stocks, edit product descriptions, and view report and history.',
    },
    {
        id: '2',
        name: 'Portfolio',
        image: ["portfolio", "portfolio-2", "portfolio-3", "portfolio-4"],
        link: 'https://github.com/vincentalexx/personal-website.git',
        deploy: '',
        langs: ['React', 'Tailwind'],
        description: 'This website content is a responsive website for portfolio using a modal for showing each of the project.'
    },
    // {
    //     id: '3',
    //     name: 'Form Ketidakhadiran Pengurus Gereja',
    //     image: [staging],
    //     link: 'https://github.com/vincentalexx/Staging.git',
    //     description: 'Form Ketidakhadiran is a form for apply for permission of activity in GII Hok Im Tong Gardujati Bandung Church.',
    // },
    {
        id: '4',
        name: 'Vern',
        image: ["vern", "vern-2", "vern-3", "vern-4", "vern-5"],
        link: 'https://github.com/vincentalexx/Vern.git',
        deploy: 'https://dta32-serverdown.pages.dev',
        langs: ['Laravel', 'React', 'Tailwind', 'PostgreSQL'],
        description: 'Vern is a car rental project that allows user to register and signin, make an rental order with e-payment, and shows the history of the orders with the status. The admin can view the grafik of the orders, add a new type of vehicle, and view the reports',
    },
    {
        id: '5',
        name: 'HashMicro',
        image: ["hashmicro", "hashmicro-2", "hashmicro-3", "hashmicro-4", "hashmicro-5", "hashmicro-6"],
        link: 'https://github.com/vincentalexx/Hashmicro.git',
        deploy: '',
        langs: ['React', 'Bootstrap'],
        description: 'This is a frontend project for the PT HashMicro Solusi Indonesia test that cloning the original website.',
    },
    {
        id: '6',
        name: 'Daniel-Scrivner',
        image: ["xylo-frontend", "xylo-frontend-2", "xylo-frontend-3", "xylo-frontend-4", "xylo-frontend-5"],
        link: 'https://github.com/vincentalexx/DanielScrivner.git',
        deploy: '',
        langs: ['React', 'Bootstrap'],
        description: 'This is a frontend project for the PT Xylo Solusi Indonesia Front End Developer test that cloning the original website.',
    },
    {
        id: '7',
        name: 'Parking-System',
        image: ["xylo-backend", "xylo-backend-2", "xylo-backend-3", "xylo-backend-4", "xylo-backend-5"],
        link: 'https://github.com/vincentalexx/Parking-System.git',
        deploy: '',
        langs: ['Laravel', 'Bootstrap', 'MySQL'],
        description: 'This is a backend project for the PT Xylo Solusi Indonesia Back End Developer test that allows user for enter and exit with showing the parking code, enter and exit time, parking duration, and the parking cost. The admin can view the reports with the date filter and export the report to excel.',
    },
    {
        id: '8',
        name: 'BookLab',
        image: ["booklab", "booklab-2", "booklab-3", "booklab-4", "booklab-5"],
        link: 'https://github.com/vincentalexx/Library.git',
        deploy: '',
        langs: ['React', 'Tailwind'],
        description: 'This is a project that allows user to search a book, see the book author, place, time, subject, and description by using API with a loading section and pagination.',
    },
    {
        id: '9',
        name: 'TitusKlein',
        image: ["titusklein", "titusklein-2", "titusklein-3", "titusklein-4", "titusklein-5", "titusklein-6", "titusklein-7", "titusklein-8", "titusklein-9", "titusklein-10", "titusklein-11", "titusklein-12", "titusklein-13", "titusklein-14", "titusklein-15", "titusklein-16", "titusklein-17"],
        link: 'https://github.com/vincentalexx/TitusKlein.git',
        deploy: '',
        langs: ['React', 'Bootstrap'],
        description: 'This is a frontend project for the PT Xylo Solusi Indonesia test that cloning the originalTitus Klein website.',
    },
];
